import{a as w,S as v,i as n}from"./assets/vendor-BjRz3xa9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const i of r)if(i.type==="childList")for(const c of i.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function t(r){const i={};return r.integrity&&(i.integrity=r.integrity),r.referrerPolicy&&(i.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?i.credentials="include":r.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function s(r){if(r.ep)return;r.ep=!0;const i=t(r);fetch(r.href,i)}})();const S="49751566-58037048f2894c5e898374fdb",q="https://pixabay.com/api/",P=15;async function f(e,o=1){const t={key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:o};try{return(await w.get(q,{params:t})).data}catch(s){throw console.error("Помилка запиту до Pixabay:",s),s}}const p=document.querySelector(".gallery");let l=null;function y(e){const o=e.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}" class="gallery-item-link">
          <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" class="gallery-image" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t.likes}</p>
          <p><b>Views:</b> ${t.views}</p>
          <p><b>Comments:</b> ${t.comments}</p>
          <p><b>Downloads:</b> ${t.downloads}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",o),l?l.refresh():l=new v(".gallery a")}function E(){p.innerHTML=""}function h(){const e=document.querySelector(".btn");e&&(e.classList.remove("is-hidden"),e.classList.add("is-visible"))}function g(){const e=document.querySelector(".btn");e&&(e.classList.add("is-hidden"),e.classList.remove("is-visible"))}function b(){const e=document.querySelector(".loader");e&&(e.classList.remove("is-hidden"),e.classList.add("is-visible"))}function d(){const e=document.querySelector(".loader");e&&(e.classList.add("is-hidden"),e.classList.remove("is-visible"))}const m=document.querySelector(".form"),A=document.querySelector('input[name="search-text"]'),M=document.querySelector(".btn");let u="",a=1;const L=15;m.addEventListener("submit",async e=>{e.preventDefault();const o=A.value.trim();if(!o){n.warning({message:"Please enter a search query!",position:"topCenter"});return}u=o,a=1,E(),g(),b();try{const t=await f(u,a);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"});return}y(t.hits),t.totalHits>L&&h()}catch{n.error({message:"An error occurred while fetching data.",position:"topCenter"})}finally{d(),m.reset()}});M.addEventListener("click",async()=>{a+=1,g(),b();const e=Date.now(),o=2e3;try{const t=await f(u,a);if(t.hits.length===0){n.info({message:"No more images to load.",position:"topCenter"});return}y(t.hits);const s=Math.ceil(t.totalHits/L);a<s&&h();const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch{n.error({message:"An error occurred while loading more images.",position:"topCenter"})}finally{const t=Date.now()-e,s=o-t;s>0?setTimeout(()=>{d()},s):d()}});
//# sourceMappingURL=index.js.map
